name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create releases and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build for linux/amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -o snap_packages_amd64.ext

      - name: Build for linux/arm64
        run: |
          GOOS=linux GOARCH=arm64 go build -o snap_packages_arm64.ext

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          body: |
            Automated release for commit ${{ github.sha }}

            ⚠️ The source code archives below may not match the latest commit. For the true latest source, use the main branch.
          draft: false
          prerelease: false
          update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload amd64 binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: snap_packages_amd64.ext
          update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload arm64 binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: snap_packages_arm64.ext
          update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 